"documentation":
  - changed-files:
    - any-glob-to-any-file: "docs/**/*"

"unittests":
  - changed-files:
    - any-glob-to-any-file: "tests/**/*"

"settings_changes":
  - changed-files:
    - any-glob-to-any-file: ["*", "!LICENSE", "!README.md"]

"enhancement":
  - changed-files:
    - any-glob-to-any-file: "cdxev/**/*"
