site_name: CycloneDX Editor Validator Tool
site_url: https://festo-se.github.io/cyclonedx-editor-validator/
repo_url: https://github.com/Festo-se/cyclonedx-editor-validator/
edit_uri: blob/main/docs/
copyright: Copyright 2024, Copyright (c) Festo SE & Co. KG

theme:
    name: readthedocs

markdown_extensions:
    - mdx_truly_sane_lists

extra_css:
  - css/festo-web-essentials.css
  - https://www.festo.com/fonts/fonts.css

nav:
    - 'Documentation':
        - 'First Steps': 'index.md'
        - 'Available commands': 'available_commands.md'
        - 'Known Limitations': 'known_limitations.md'
    - 'Further Information':
        - 'Maintainers': 'maintainers.md'
        - 'Contributing': 'CONTRIBUTING.md'
